# Generated by Django 5.0 on 2025-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='folder',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='isManagement',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('departament', models.ManyToManyField(blank=True, related_name='departments', to='users.department')),
            ],
        ),
    ]
