version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
