# Generated by Django 5.0 on 2025-04-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_system', '0002_initial'),
        ('users', '0004_department_folder_department_ismanagement_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='group',
        ),
        migrations.AddField(
            model_name='folder',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='folders', to='users.department'),
        ),
        migrations.AddField(
            model_name='folder',
            name='path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
