# Generated by Django 5.0 on 2025-04-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_initial'),
        ('users', '0004_department_folder_department_ismanagement_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='users.department', verbose_name='Группа'),
        ),
    ]
